repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
      - id: black-jupyter
        types: [jupyter]
        args: [--line-length=85]  # notebooks (for sphinx docs)

  - repo: https://github.com/pycqa/pylint
    rev: v4.0.0
    hooks:
      - id: pylint

ci:
  autoupdate_branch: dev
